// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace todo.macOS
{
	public partial class SYFlatButton : NSButton
	{
		public SYFlatButton (IntPtr handle) : base (handle)
		{
		}
	}
}
